---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Proxies for analytics cdn and data ingestion endpoints

Parameters:

  ControlRootUrl:
    Type: String
    Default: 'cyclic.sh'
    Description: RootUrl to host api and ui for Cyclic control plane eg cyclic.sh

  ControlSslCertCf:
    Type: String #must be a us-east-1 cert because cloudfront
    Default: 'arn:aws:acm:us-east-1:542703605194:certificate/45cafc06-56af-4184-9903-35459f4411d8'
    Description: ACM cert arn for *.cyclic.sh and cyclic.sh in us-east-1 for CloudFront

Resources:
  WWWProxyCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_100
        Aliases:
          - !Sub '${ControlRootUrl}'
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - OPTIONS
            - GET
            - POST
            - DELETE
            - PUT
            - PATCH
          MaxTTL: 0
          MinTTL: 0
          DefaultTTL: 0
          ForwardedValues:
            Cookies:
              Forward: all
            QueryString: true
          TargetOriginId: www
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        IPV6Enabled: true
        Origins:
          - DomainName: 'www.cyclic.sh'
            Id: www
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
            OriginPath: ''
        ViewerCertificate:
          AcmCertificateArn: !Ref ControlSslCertCf
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only

  SiteAliasesData:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub '${ControlRootUrl}.'
      RecordSets:
        - Name: !Sub '${ControlRootUrl}'
          Type: A
          AliasTarget:
            DNSName: !GetAtt 'WWWProxyCloudfront.DomainName'
            HostedZoneId: Z2FDTNDATAQYW2 # Hosted Zone Id for '*.cloudfront.net.'

